[env]
_.source = './.envrc'

[tools]
task = "latest"
jq = "latest"
python = "3.13"
uv = "latest"
gitleaks = "latest"
yq = "latest"
npm = "latest"
node = "22.22"
gh = "latest"
lychee = "latest"

[tools."github:asciinema/agg"]
version = "latest"
asset_pattern = "agg-aarch64-apple-darwin"
bin = "agg"

# [tools."github:infisical/cli"]
# version = "latest"
# asset_pattern = "cli_*_darwin_arm64.tar.gz"
# bin = "infisical"
