[env]
_.source = './.envrc'

[tools]
task = "latest"
jq = "latest"
python = "3.13"
uv = "latest"
gitleaks = "latest"
yq = "latest"
npm = "latest"
node = "latest"

[tools."github:asciinema/agg"]
version = "latest"
asset_pattern = "agg-aarch64-apple-darwin"
bin = "agg"